### ISSUE TITLE
is there any possiblity to add stream result on "connection.transaction" ?

### ISSUE THREAD

**Issue by behroozshafiabadi** [sagiegurari/simple-oracledb#11]
i use multi select query to get data. now i want to use streams to pipe results...i must to use stream result in any sub query or i can use it with whole transaction?

**Comment by sagiegurari** [comment]
multi select? can you show me a small code snippet so i'll understand what you mean?

**Comment by behroozshafiabadi** [comment]
`connection.transaction([
                function (callback) {
                    connection.query(query, {}, {
                            resultSet: true,
                            autoCommit: true
                        }, callback
                    )
                },
                function (callback) {
                    connection.query(query2, {}, {
                            resultSet: true,
                            autoCommit: true
                        }, callback
                    )
                }
            ], function (err, output) {
                if (err) {
                    log.error(config.e[1], err);
                    u.ajaxWriteError(response, config.e[1]);
                } else {
                    u.ajaxWriteSuccess(response, {
                        data: output
                    });
                }
                dbi.releaseConnection(connection, function (err) {
                    if (err)
                        log.error(config.e[1], err);
                });
            })`
something like this

**Comment by behroozshafiabadi** [comment]
connection.transaction([
function (callback) {
connection.query(query, {}, {
resultSet: true,
autoCommit: true
}, callback
)
},
function (callback) {
connection.query(query2, {}, {
resultSet: true,
autoCommit: true
}, callback
)
}
], function (err, output) {
if (err) {
log.error(config.e[1], err);
u.ajaxWriteError(response, config.e[1]);
} else {
u.ajaxWriteSuccess(response, {
data: output
});
}
dbi.releaseConnection(connection, function (err) {
if (err)
log.error(config.e[1], err);
})
})

**Comment by behroozshafiabadi** [comment]
some code like transaction execut pharallel !
`connection.transaction([
  function insertSomeRows(callback) {
    connection.insert(...., function (error, results) {
      //some more inserts....
      connection.insert(...., callback);
    });
  },
  function insertSomeMoreRows(callback) {
    connection.insert(...., callback);
  },
  function doSomeUpdates(callback) {
    connection.update(...., callback);
  },
  function runBatchUpdates(callback) {
    connection.batchUpdate(...., callback);
  }
], function onTransactionResults(error, output) {
  //continue flow...
});`

**Comment by sagiegurari** [comment]
please format it using github markdown, because I can't read it.

**Comment by sagiegurari** [comment]
wait... so you mean multiple connection.query? if so, there is no stream for connection.transaction/connection.run only to connection.query.
so multiple streams.
also if you are not doing any update/insert so you don't need a transaction, you can use connection.run instead of connection.transaction
