### ISSUE TITLE
about data streaming performance

### ISSUE THREAD

**Issue by behroozshafiabadi** [sagiegurari/simple-oracledb#13]
when i use streaming feature in oracledb,and set timer on it,its take ~17 ms to gets firts row and ~320 to end event triggered and whole data comes out.(objectMode is true)
but in normal use case when i use traditional way without stream result,its only take about ~25 ms to get whole data.
what is wrong in this use case ?
everything is ok ?
I thought streaming is more powerful and faster

**Comment by sagiegurari** [comment]
Ya the performance should be not as good since i have to use getRow one at a time. However not sure about your numbers, will run some tests as well when i have time.
The stream is meant to save on memory, not time. So the decision on what to use is case by case basis.

**Comment by sagiegurari** [comment]
by the way if you don't have LOBs in your query, check the connection.queryStream in the original oracledb library.
I wrote it as well, but there I don't convert LOBs to string/buffer so it should be a bit faster and give you same functionality.

**Comment by behroozshafiabadi** [comment]
@sagiegurari thank to your notation
no i have not any LOBs type column
is that you mean time mybe increase and stream be faster than non stream query ?

**Comment by sagiegurari** [comment]
if no LOBs, try using connection.queryStream and see if it improves your overall performance instead of connection.query.

**Comment by behroozshafiabadi** [comment]
@sagiegurari ok i check it

**Comment by behroozshafiabadi** [comment]
no sensible effect :)
thank you

**Comment by sagiegurari** [comment]
too bad.
i wrote down an item for myself to check and see if i can do something about the performance, because I believe there is some solution there.
