### ISSUE TITLE
query function returns columns with value null as undefined

### ISSUE THREAD

**Issue by volkmarbuehringer** [sagiegurari/simple-oracledb#15]
#### Problem Description
query function returns columns with value null as undefined

the execute function of oracledb returns the columns correctly as nulls

#### Code Example

con.query( "select * from test",[],(err,result)=>{
the rows in result will have undefined instead of null

} );

**Comment by sagiegurari** [comment]
Will check and fix today/tommorrow hopefully

**Comment by sagiegurari** [comment]
fixed. check version 1.1.36
please tell me of any issues.

**Comment by sagiegurari** [comment]
i'm closing this issue.
if there are any more problems please reopen or open a new case. 
thanks
