### ISSUE TITLE
delay in fetching data issues 

### ISSUE THREAD

**Issue by behroozshafiabadi** [sagiegurari/simple-oracledb#19]
#### 
Hi @sagiegurari i need your help
i work in Api server that responsable to fetch data from db and send it.
assume my table has 1,500,000 rows
it take about 50 seconds to server receive all data from db...is that normal ?
in apps like dbForge...the execution time is about 1 second
is it dependent to network infrastructure ? or any method in simple oracle db to make it faster ?
thank you

**Comment by sagiegurari** [comment]
are you streaming it (option streamResults=true)?

**Comment by behroozshafiabadi** [comment]
no i give data with resultSet method

**Comment by sagiegurari** [comment]
can you show me code snippet because if you are not using stream, basically it means i'm fetching 1.5 million rows into the memory which is really bad.
that is what streaming is for.

**Comment by behroozshafiabadi** [comment]
if i say using stream another branch of issue comes...
that node js response.write ends suddenly!
but if we reject  streaming...50-60 seconds is horrible
in normal mode :
````js
dbi.getConnection(c.dbConfig, function (err, connection) {
                    if (err) {
                        done(err);
                        //log.error(config.e[1], err);
                    } else {
                        connection.execute(input.query, {}, {
                            autoCommit: true
                        }, function (err, data) {
                            if (err) {
                                done(err);
                                //      log.error(config.e[1], err);
                            } else {
                                job.remove(function (err) {
                                    if (err) throw err;
                                    setTimeout(function () {
                                        done();
                                        console.log('removed completed job #%d', job.id);
                                    }, 50000);
                                });
                            }
                            dbi.releaseConnection(connection, function (err) {
                                if (err) {
                                    done(err);
                                    //log.error(err);
                                }
                            })
                        })
                    }
                });
````
in streaming mode :
````js
dbi.getConnection(c.dbConfig, function (err, connection) {
            if (err) {
                done(err);
                log.error(config.e[1], err);
            } else {
                var checkForDataSend = true;
                if (input.amount == 'all') {
                    response.writeHead(200, {'Content-Type': 'text/plain'});
                    //response.writeContinue();
                    var stream = connection.query(input.query, [], {streamResults: true});
                    stream.on('data', function (row) {
                        checkForDataSend = response.write(JSON.stringify(row) + ",");
                    });
                    stream.on('end', function () {
                        //job.set('data', '', done);
                        console.log("now fetch data is ended");
                        response.end();
                        dbi.releaseConnection(connection, function (err) {
                            if (err) {
                                done(err);
                            }
                        })
                    });
                    stream.on('error', function (err) {
                        dbi.releaseConnection(connection, function (err) {
                            if (err) {
                                done(err);
                            }
                        })
                    });
                    response.on('close', function () {
                        console.log("response close event sent")
                    })
})
````

**Comment by sagiegurari** [comment]
your streaming code from quick glance looks correct from db point of view, but not from the response.write point of view.
See nodejs docs for more info:
[stream.write](https://nodejs.org/api/stream.html#stream_writable_write_chunk_encoding_callback
)
Basically you are doing a 'write' before the response can handle more write operations.
Specifically from nodejs docs

> The return value indicates whether the written chunk was buffered internally and the buffer has exceeded the highWaterMark configured when the stream was created. If false is returned, further attempts to write data to the stream should be paused until the 'drain' event is emitted.

by the way, not part of this issue, but if you are using pool, you can do pool.run, if you are not (like I see above, which is less recommended but anyway...) you can do oracledb.run(connAttrs, action, callback); so you don't need to release the connection on your own

https://github.com/sagiegurari/simple-oracledb#OracleDB+run

**Comment by behroozshafiabadi** [comment]
thank for your nav you are amazing

**Comment by behroozshafiabadi** [comment]
@sagiegurari  can you help me in this case ?
of course it's not about this issue or even oracledb!! but with res drain my response close early before whole data fetched!
have you any issue ?
````js
var stream = connection.query(input.query, [], {streamResults: true});
                    stream.on('data', function (row) {
                        if (checkForDataSend) {
                            checkForDataSend = response.write(JSON.stringify(row) + ",",'utf-8');
                        } else {
                            tmpData += JSON.stringify(row) + ",";
                        }
                    });
                    response.on('drain', function () {
                        checkForDataSend = true;
                        //response.write(tmpData,'utf-8');
                        tmpData = '';
                    });
                    stream.on('end', function () {
                        //job.set('data', '', done);
                        console.log("now fetch data is ended");
                        selectCounter--;
                        if (selectCounter === 0)
                            stopFlagForInsert = false;
                        response.end();
                        dbi.releaseConnection(connection, function (err) {
                            if (err) {
                                done(err);
                            }
                        })
                    });
````

**Comment by sagiegurari** [comment]
on drain you are supposed to write the temp data you have (you commented that out).
on stream.end you just need to close the connection if you can't yet write to the response in wihch case you need to end the response in the drain that comes after the close.
that is why pipe is a better solution than all those event listeners.
Here is a good example how to transform data and using pipe
https://www.sandersdenardi.com/readable-writable-transform-streams-node/

**Comment by behroozshafiabadi** [comment]
but stream type of oracle db is object mode that i think cant be piped if i not wrong!

**Comment by sagiegurari** [comment]
Im not sure i've heard of that but try to google a bit
