### ISSUE TITLE
When executing batchInsert, DB errors are not available in the callback err param

### ISSUE THREAD

**Issue by karthikrock** [sagiegurari/simple-oracledb#20]
```
connection.batchInsert('<INSERT STATEMENT>', [{ //first row values
                id: 110,
                name: 'A'
            },
            { //second row values
                id: 111,
                name: 'B'
            }
        ], {
            autoCommit: false
        }
    },
    function onResults(err, output) {
        if (err) {
            console.log(JSON.stringify(err)); //prints empty object when there is a DB error- {}
        }
    });
```

It handles the error however there is nothing in the err object to debug/understand what kind of DB error occurred. Version: "simple-oracledb": "~1.1.39".

Is it fixed in any of the newer releases ? Or was it ever reported as an issue ?

**Comment by sagiegurari** [comment]
From my tests it should work fine.
The issue I'm seeing is that you are trying to stringify an error object but that is not the right way to work with errors.
for example this would also result in an empty object

````js
JSON.stringify(new Error('test')); // -> {}
````

So don't use errors like that, use the error.message/error.stack/...
See more in mdn: https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Error

**Comment by sagiegurari** [comment]
closing this one. if you have any issues please open a new issue.

**Comment by karthikrock** [comment]
My bad! yes stringifying Error object makes it {}. I was able to extract the error using the properties. :)
