### ISSUE TITLE
ResultSet 

### ISSUE THREAD

**Issue by ceomedx** [sagiegurari/simple-oracledb#21]
Hi 100000 line Can you give an example for a function returning sys_refcursor?

Example : 
BEGIN :result := PACKAGENAME.SELECT_USER_LIST(); END;

**Comment by sagiegurari** [comment]
I dont provide extra capabilities specific to cursors.
So whatever is supported by the oracledb library is what you have.
However it sounds like you would want to use streams to prevent loading so many rows to the memory

[Connection.query](https://github.com/sagiegurari/simple-oracledb#Connection+query)

**Comment by sagiegurari** [comment]
If there are no more comments I'll be closing this thread
