### ISSUE TITLE
investigate performance improvement by using new executemany

### ISSUE THREAD

**Issue by sagiegurari** [sagiegurari/simple-oracledb#22]
to be used if available in batch operations.

**Comment by sagiegurari** [comment]
implemented in 1.2.1

**Comment by cjbj** [comment]
How do you find the performance compared with your old implementation?

**Comment by sagiegurari** [comment]
actually having some issues making it work. I'll have to stop in the middle and continue this later on... strange however that i'm getting an error which i'm not sure what exactly it means since it is not pointing to which field in which insert/update command.
this is the error:
"NJS-011: encountered bind value and type mismatch", // errBindValueAndTypeMismatch

will have to understand what i'm doing wrong, but might take a while as I no longer have access to oracle and I run tests via docker in travis which takes forever.

**Comment by cjbj** [comment]
Nice!

It would have been great if `options.useExecuteMany` could have defaulted to *true*.  Maybe once you've checked the performance benefits ...?

**Comment by sagiegurari** [comment]
it will be true once i feel its stable enough and well tested (my code i mean)

**Comment by cjbj** [comment]
@sagiegurari how it's going?

**Comment by sagiegurari** [comment]
executeMany is now turned on by default.

**Comment by cjbj** [comment]
Yay!
