### ISSUE TITLE
Error: Callback not provided

### ISSUE THREAD

**Issue by jay-jlm** [sagiegurari/simple-oracledb#25]
Trying to convert some existing code to use promises instead of callbacks.
Got the following error: 

>  Connection failed - Error: Callback not provided. 

Code: 
```
const oracledb = require('oracledb')
const SimpleOracleDB = require('simple-oracledb')

SimpleOracleDB.extend(oracledb)
const onConnectError = error => logger.error(`Connection failed - ${error}`)
const onQueryError = error => logger.error(`Query failed - ${error}`)
const onQueryResult = results => {
  console.log(`Rows received: ${results.length}`)
}

exports.execQuery = () => oracledb.getConnection(connectionConfig)
  .then(connection => {
    connection.query(createQuery(), [], {
      splitResults: true,
      bulkRowsAmount: 50,
    })
      .then(onQueryResult)
      .catch(onQueryError)
  })
  .catch(onConnectError)
```

**Comment by sagiegurari** [comment]
splitResults does not support callback.
reason is that with splitResults, your callback is called multiple times, each time with another bulk set of results.
In promises, you can't call the then multiple times.

**Comment by jay-jlm** [comment]
Thank you.
Maybe make this limitation more explicit in the Readme page?

**Comment by sagiegurari** [comment]
just the query. the split option is only gor query.
I'll update the docs to be more clear

**Comment by jay-jlm** [comment]
Thanks, I suggest put this info in the information in the method documentation, I guess there's where ppl will look if they have the same problem I did.

**Comment by sagiegurari** [comment]
It was already documented in the js docs:
https://github.com/sagiegurari/simple-oracledb/blob/master/docs/api.md#connectionquerysql-bindparams-options-callback--resultsetreadstream--promise

but i added to the example in the main readme as well.
