### ISSUE TITLE
bound param of value null causes error

### ISSUE THREAD

**Issue by commi** [sagiegurari/simple-oracledb#31]
### Describe The Bug
If the parameter of a prepared statement has the value `null` an error occurs int he library code

### To Reproduce
* query `SELECT :a`  (does not have to be executed)
* bind **:a** to `null`

### Error Stack

```console
batchUpdate error: TypeError: Cannot read property 'getDate' of null
    at Connection.generateBindDefinitionEntry (/home/till/IdeaProjects/bas-syncserver/server/node_modules/simple-oracledb/lib/connection.js:1691:25)
    at Connection.generateBindDefinitions (/home/till/IdeaProjects/bas-syncserver/server/node_modules/simple-oracledb/lib/connection.js:1740:18)
    at Connection.insertOrUpdate (/home/till/IdeaProjects/bas-syncserver/server/node_modules/simple-oracledb/lib/connection.js:581:14)
```

### Code Sample

```js
oracleconnection.batchUpdate(`SELECT :a`,[{a: null}]);
```

The reason is here:

```js
Connection.prototype.generateBindDefinitionEntry = function (bindDefinitions, key, item) {
 if (typeof item === 'object') {
        if (typeof item.getDate === 'function') {

```

as `null` is considered type _object_

**Comment by commi** [comment]
Hi, i'd love to, but wont, because i actually am not sure what to do with an `item` of type `null` here. I mean what to do with `bindDefinitions` if anything.

**Comment by cjbj** [comment]
In node-oracledb:
```
    const sql = `select :a from dual`;
    const binds = [null];
    const options = { outFormat: oracledb.OUT_FORMAT_OBJECT };
    const result = await connection.execute(sql, binds, options);
    console.dir(result, { depth: null }); 
```
gives
```
 { metaData: [ { name: ':A' } ], rows: [ { ':A': null } ] }
```

**Comment by cjbj** [comment]
@sagiegurari If it helps, you can create a free DB using Oracle Cloud https://www.oracle.com/cloud/free/  The top level wording is confusing IMHO but the bottom two boxes have the details. You start with a free trial to all services. At the end of the trial you get to keep using free DB and free compute and some other free bits and pieces forever.
