### ISSUE TITLE
oracledb.getConnection does not work with promises

### ISSUE THREAD

**Issue by volkmarbuehringer** [sagiegurari/simple-oracledb#5]
#### Problem Description

oracledb 1.10.1 works with promises, but after extending with simple-oracledb,
it errors with "invalid number of parameters"

oracledb.getConnection( { ..} ).then( ( con ) => {

});

#### Code Example

````js
//paste code here
````

**Comment by sagiegurari** [comment]
ya, only recently i fixed the connection for that, but didn't for the pool.
will fix and update you.

**Comment by sagiegurari** [comment]
fixed. checkout version 0.1.83

**Comment by sagiegurari** [comment]
I'm closing this case, if you have any issue please reopen it.
