### ISSUE TITLE
query command return only first 100 row

### ISSUE THREAD

**Issue by behroozshafiabadi** [sagiegurari/simple-oracledb#8]
hi @sagiegurari 
when i use  connection.query its only return first 100 row...is that any property to change this behavior ???
without simple oracledb i solve it with using resultset

**Comment by sagiegurari** [comment]
add options: resultset true

````js
connection.query('SELECT * FROM SOME_TABLE', [], {
    resultSet: true
  }, function (error, jsRows) {
    console.log(jsRows);
});
````
